[phases.setup]
nixPkgs = ["python311", "gcc", "stdenv"]

[phases.install]
cmds = ["python3 -m venv /app/venv", "source /app/venv/bin/activate && pip install --upgrade pip", "source /app/venv/bin/activate && pip install -r requirements.txt"]

[phases.build]
cmds = []

