[phases.setup]
nixPkgs = ["python311", "curl"]

[phases.install]
cmds = ["curl -sS https://bootstrap.pypa.io/get-pip.py | python3", "python3 -m pip install --upgrade pip", "python3 -m pip install -r requirements.txt"]

[phases.build]
cmds = []

